baseURL = "https://batu.bangunan.co/"
languageCode = "id"
title = "Batu Bangunan | Jual Batu Kali Batu Split Cor Batu Pondasi Batu Belah Terdekat"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Supplier Batu Bangunan Berkualitas - Jual Batu Kali, Batu Split, Batu Pondasi, dan Batu Belah dengan harga bersaing dan pengiriman gratis ongkir juga bongkar."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual batu kali", "batu split", "batu pondasi", "batu belah", "batu koral cor", "batu bangunan", "batu alam murah", "batu pondasi bangunan"]
  base_price = 300000
  price_range = 100000
  free_shipping = true
  materials = [
  "Batu Kali",
  "Batu Split",
  "Batu Pondasi",
  "Batu Belah",
  "Batu Koral Cor",
  "Batu Screening",
  "Batu Alam"
  ]
  categories = ["Batu Bangunan", "Batu Pondasi", "Batu Split", "Batu Belah", "Batu Kali", "Batu Screening", "Batu Alam"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Pengiriman"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Material bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk jenis batu yang tidak sesuai.",
  "Material yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Supplier Batu Bangunan Terpercaya"
  hero_description = "Kami menjual berbagai jenis material batu berkualitas untuk kebutuhan konstruksi bangunan. Solusi ideal untuk pondasi bangunan yang kuat, dengan layanan gratis ongkir dan bongkar."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Batu"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan batu berkualitas tinggi dengan harga murah dan layanan pengiriman gratis ongkir dan bongkar. Juga, konsultasi gratis untuk membantu Anda memilih jenis batu yang tepat untuk proyek bangunan Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "batu.bangunan.co menawarkan berbagai jenis batu berkualitas seperti batu kali, batu split cor, batu pondasi, dan batu belah. Kami mengutamakan kepuasan pelanggan dengan produk berkualitas dan harga bersaing. Pilih kami untuk memenuhi kebutuhan batu proyek bangunan Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya membeli batu kali dari batu.bangunan.co untuk proyek rumah saya, dan hasilnya sangat memuaskan.|Saya memesan batu kali dari batu.bangunan.co untuk proyek pembangunan rumah, dan saya sangat puas.|Saya menggunakan batu kali dari batu.bangunan.co untuk konstruksi rumah saya, dan hasilnya luar biasa.} {Kualitas batu {sangat baik|unggul|terbaik|luar biasa|prima}|Mutu batu yang diterima {hebat|istimewa|berkualitas tinggi|menakjubkan|superior}} dan {pengirimannya tepat waktu|pengiriman sesuai jadwal|proses pengirimannya {cepat|efisien|tepat}.|proses pengirimannya berjalan {lancar|aman|teratur}}"
  response = "{Terima kasih atas kepercayaan Anda! Kami senang dapat menyediakan batu berkualitas untuk proyek rumah Anda.|Kami menghargai kepercayaan Anda! Kami gembira Anda puas dengan produk kami.|Kami sangat menghargai kepercayaan Anda! Senang membantu proyek Anda dengan produk berkualitas.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Dewi|Ayu|Tari|Fitri|Ratna|Lina|Mira|Nina|Dina}"
  message = "{batu.bangunan.co sangat membantu dalam memilih jenis batu yang tepat untuk proyek rumah saya.|Saya sangat terbantu oleh batu.bangunan.co dalam memilih jenis batu yang cocok untuk proyek saya.|batu.bangunan.co memberikan rekomendasi batu yang tepat untuk proyek konstruksi rumah saya.} {Material yang saya beli {berkualitas|bermutu tinggi|kokoh|terbaik|luar biasa}|Batu yang saya dapatkan {kokoh|bagus|berkualitas|prima|unggul}} dan {sesuai dengan kebutuhan saya|pas untuk proyek saya|memenuhi harapan saya|cocok dengan keperluan saya}."
  response = "{Kami sangat menghargai ulasan Anda! Senang mendengar Anda puas dengan produk kami.|Terima kasih banyak atas ulasan Anda. Kami senang dapat membantu Anda.|Kami sangat senang Anda puas dengan batu dari batu.bangunan.co}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Budi|Andi|Eko|Rudi|Agus|Hendra|Dedi|Samsul|Fajar}"
  message = "{Batu dari batu.bangunan.co sangat cocok untuk proyek perumahan saya.|Saya menggunakan batu dari batu.bangunan.co untuk proyek perumahan saya dan hasilnya luar biasa.|Batu dari batu.bangunan.co sesuai dengan kebutuhan proyek saya.} {Proses pembelian dan pengirimannya {cepat|sangat cepat|efisien|lancar}|Pembelian dan pengiriman {tepat waktu|efisien|tanpa masalah}} dan {bisa bayar COD|tersedia pilihan pembayaran COD|bisa dibayar dengan sistem COD}."
  response = "{Terima kasih! Kami berkomitmen menyediakan batu berkualitas dengan layanan terbaik.|Kami sangat menghargai ulasan Anda! Terima kasih atas kepercayaan Anda.|Senang mendengar Anda puas dengan layanan dan produk kami. Terima kasih!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Joko|Budi|Eko|Rudi|Agus|Hendra|Dedi|Samsul|Fajar}"
  message = "{Saya sangat puas dengan batu pondasi dari batu.bangunan.co.|Batu pondasi dari batu.bangunan.co sangat memuaskan.|Saya menggunakan batu pondasi dari batu.bangunan.co dan hasilnya luar biasa.} {Kualitasnya sangat baik|Mutunya luar biasa|Batu ini sangat berkualitas} dan {sesuai untuk proyek konstruksi bangunan saya|cocok dengan kebutuhan proyek saya|ideal untuk konstruksi bangunan saya}."
  response = "{Senang mendengar Anda puas dengan produk kami. Terima kasih atas kepercayaannya!|Terima kasih! Kami senang dapat menyediakan batu pondasi berkualitas untuk proyek Anda.|Kami sangat menghargai kepercayaan Anda. Senang mendengar Anda puas dengan produk kami!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Dewi|Siti|Ayu|Tari|Fitri|Ratna|Lina|Mira|Nina}"
  message = "{Pelayanan batu.bangunan.co sangat memuaskan.|Saya sangat puas dengan pelayanan batu.bangunan.co.|batu.bangunan.co memberikan layanan yang sangat baik.} {Material batu yang saya beli {berkualitas|bermutu tinggi|kokoh|prima|sangat baik}|Batu yang saya pesan {sangat sesuai|berkualitas|memenuhi harapan saya|pas dengan kebutuhan saya}} dan {sesuai dengan harapan saya|tepat seperti yang saya inginkan|sesuai dengan ekspektasi saya}."
  response = "{Terima kasih! Kami senang dapat membantu mewujudkan proyek Anda dengan batu berkualitas.|Terima kasih atas ulasannya! Kami sangat menghargai kepercayaan Anda.|Senang mendengar Anda puas dengan layanan dan produk kami}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Joko|Budi|Andi|Rudi|Agus|Hendra|Samsul|Fajar|Dedi}"
  message = "{Batu dari batu.bangunan.co sangat sesuai dengan kebutuhan proyek renovasi rumah saya.|Saya memesan batu dari batu.bangunan.co dan hasilnya luar biasa untuk proyek renovasi rumah saya.|Batu dari batu.bangunan.co cocok dengan renovasi rumah yang sedang saya kerjakan.} {Proses pengirimannya cepat dan aman|Pengiriman batu sangat cepat dan aman|Pengirimannya tepat waktu dan berjalan dengan aman}."
  response = "{Kami senang mendengar bahwa Anda puas dengan produk batu kami. Terima kasih atas ulasannya!|Terima kasih atas ulasan positifnya! Kami senang dapat membantu proyek Anda.|Senang mendengar Anda puas dengan batu dari batu.bangunan.co. Terima kasih!}"
  rating = 5

[[params.tabelItems]]
  name = "Batu Kali"
  price = "250.000 /m3"
[[params.tabelItems]]
  name = "Batu Split"
  price = "280.000 /m3"
[[params.tabelItems]]
  name = "Batu Pondasi"
  price = "235.000 /m3"
[[params.tabelItems]]
  name = "Batu Belah"
  price = "235.000 /m3"
[[params.tabelItems]]
  name = "Batu Screening"
  price = "280.000 /m3"
[[params.tabelItems]]
  name = "Batu Alam"
  price = "300.000 /m3"
  
[params.appliList]
  "Batu Kali" = "digunakan untuk pondasi, struktur bangunan"
  "Batu Split" = "digunakan untuk pengecoran bangunan dan jalan"
  "Batu Pondasi" = "cocok untuk pondasi rumah dan bangunan"
  "Batu Belah" = "untuk pondasi, pengerasan jalan"
  "Batu Screening" = "digunakan untuk cor beton dalam pembangunan"
  "Batu Alam" = "untuk dekorasi taman, pagar, dinding"

[params.kegunaanList]
  "Batu Kali" = "cocok untuk pondasi bangunan dengan struktur yang kuat"
  "Batu Split" = "digunakan dalam pengecoran untuk memperkuat struktur beton"
  "Batu Pondasi" = "digunakan sebagai bahan utama pondasi rumah dan bangunan"
  "Batu Belah" = "untuk pengerasan jalan atau landasan proyek"
  "Batu Screening" = "digunakan untuk pengecoran beton non struktural yang kuat"
  "Batu Alam" = "digunakan untuk estetika dekorasi taman atau eksterior bangunan"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Supplier Batu Kali, Split Cor & Pondasi | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"